# SF Salaries Exercise

We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle!  The tasks will  may get complicated

** Import pandas as pd.**

In [ ]:
import pandas as pd

** Read Salaries.csv as a dataframe called sal.**

In [ ]:
df = pd.read_csv('Salaries.csv', low_memory=False)

** Check the head of the DataFrame. **

In [ ]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

** Use the .info() method to find out how many entries there are.**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

**What is the average BasePay ?**

In [ ]:
df['BasePay'] = pd.to_numeric(df['BasePay'], errors='coerce')
print(f"The average BasePay is: {df['BasePay'].mean():.2f}")

The average BasePay is: 66325.45

** What is the highest amount of OvertimePay in the dataset ? **

In [ ]:
df['OvertimePay'] = pd.to_numeric(df['OvertimePay'], errors='coerce')
print(f"The highest amount of OvertimePay is: {df['OvertimePay'].max():.2f}")

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [ ]:
joseph_driscoll_job_title = df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']
print(joseph_driscoll_job_title.iloc[0])

CAPTAIN, FIRE SUPPRESSION

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [ ]:
joseph_driscoll_total_pay_benefits = df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']
print(joseph_driscoll_total_pay_benefits.iloc[0])

270324.91

** What is the name of highest paid person (including benefits)?**

In [ ]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [11]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [12]:
df.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

** How many unique job titles are there? **

In [13]:
df['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

** What are the top 5 most common jobs? **

In [14]:
df['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [15]:
df[df['Year'] == 2013]['JobTitle'].value_counts()

JobTitle
Transit Operator                2295
Special Nurse                   1445
Registered Nurse                1231
Public Svc Aide-Public Works     859
Custodian                        789
                                ...
IS Technician Assistant            1
Chief, Fire Department             1
Braillist                          1
Victim & Witness Technician        1
Senior Assessment Clerk            1
Name: count, Length: 1051, dtype: int64

** How many people have the word Chief in their job title? (This is pretty tricky) **

In [16]:
df['JobTitle'].apply(lambda x: 'chief' in x.lower()).sum()

np.int64(627)

** Bonus: Is there a correlation between length of the Job Title string and Salary? **

In [19]:
df['title_len'] = df['JobTitle'].apply(len)

In [20]:
df[['title_len','TotalPayBenefits']].corr()

                  title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000

# Great Job!